export enum OrganizationAppTypes {

  ZENDESK_SUPPORT = 'ZENDESK_SUPPORT',
  ZENDESK_SELL = 'ZENDESK_SELL',
  ZENDESK_SUNSHINE = 'ZENDESK_SUNSHINE',
  ZENDESK_SUPPORT_END_USER = 'ZENDESK_SUPPORT_END_USER',
  ZENDESK_CHAT_WIDGET = 'ZENDESK_CHAT_WIDGET',
  ZENDESK_CHAT = 'ZENDESK_CHAT',
  GOCARDLESS = 'GOCARDLESS',
  STRIPE = 'STRIPE',
  PIPEDRIVE = 'PIPEDRIVE',
  SENDGRID = 'SENDGRID',
  TWILIO_SMS = 'TWILIO_SMS',
}
