export const INIT_PROCESS_WORKFLOW_FORM = 'INIT_PROCESS_WORKFLOW_FORM';
export const UPDATE_PROCESS_WORKFLOW_FORM_STATE = 'UPDATE_PROCESS_WORKFLOW_FORM_STATE';
export const CLOSE_PROCESS_WORKFLOW_FORM = 'CLOSE_PROCESS_WORKFLOW_FORM';