export const GET_ZDTICKETS_REQUEST = 'GET_ZDTICKETS_REQUEST';
export const GET_ZDTICKETS_SUCCESS = 'GET_ZDTICKETS_SUCCESS';
export const GET_ZDTICKETS_ERROR = 'GET_ZDTICKETS_ERROR';

export const CREAT_ZDTICKET_REQUEST = 'CREAT_ZDTICKET_REQUEST';
export const CREAT_ZDTICKET_SUCCESS = 'CREAT_ZDTICKET_SUCCESS';
export const CREAT_ZDTICKET_ERROR = 'CREAT_ZDTICKET_ERROR';

export const UPDATE_ZDTICKET_REQUEST = 'UPDATE_ZDTICKET_REQUEST';
export const UPDATE_ZDTICKET_SUCCESS = 'UPDATE_ZDTICKET_SUCCESS';
export const UPDATE_ZDTICKET_ERROR = 'UPDATE_ZDTICKET_ERROR';

export const CREATE_ZDTICKET_COMMENT_REQUEST = 'CREATE_ZDTICKET_COMMENT_REQUEST';
export const CREATE_ZDTICKET_COMMENT_SUCCESS = 'CREATE_ZDTICKET_COMMENT_SUCCESS';
export const CREATE_ZDTICKET_COMMENT_ERROR = 'CREATE_ZDTICKET_COMMENT_ERROR';

export const GET_ZDTICKET_COMMENTS_REQUEST = 'GET_ZDTICKET_COMMENTS_REQUEST';
export const GET_ZDTICKET_COMMENTS_SUCCESS = 'GET_ZDTICKET_COMMENTS_SUCCESS';
export const GET_ZDTICKET_COMMENTS_ERROR = 'GET_ZDTICKET_COMMENTS_ERROR';