export enum WTriggerTypeEnum {
  ENTITY_EVENT = 'ENTITY_EVENT',
  CRON = 'CRON',
}

export enum WTriggerEntityEventEnum { 
  CREATED = 'CREATED',
  BEFORE_CREATE = 'BEFORE_CREATE',
  UPDATED = 'UPDATED',
  BEFORE_UPDATE = 'BEFORE_UPDATE',
  DELETED = 'DELETED',
  BEFORE_DELETE = 'BEFORE_DELETE',
  STAGE_UPDATED = 'STAGE_UPDATED',
  ASSOCIATION_CREATED = 'ASSOCIATION_CREATED',
  ASSOCIATION_UPDATED = 'ASSOCIATION_UPDATED',
  ASSOCIATION_DELETED = 'ASSOCIATION_DELETED',
  PARENT_ASSOCIATION_CREATED = 'PARENT_ASSOCIATION_CREATED',
  PARENT_ASSOCIATION_UPDATED = 'PARENT_ASSOCIATION_UPDATED',
  PARENT_ASSOCIATION_DELETED = 'PARENT_ASSOCIATION_DELETED',
}

export enum WRecordSelectorTypeEnum {
  FROM_EVENT = 'FROM_EVENT',
  FUNC = 'FUNC',
}

export enum WCronJobExecStatusEnum {
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}